
###
//Lgin API
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "zumar2014@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/token

###
DELETE  http://localhost:5000/logout

###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name":"Zumardi Rahmanx",
    "email": "zumar2014@gmail.come",
    "gender": "Male",
    "password": "123456",
    "confPassword": "123456"
}


### 
//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Indah Hariani",
    "email": "indah@gmail.com",
    "gender": "Female",
    "password": "123456",
    "confirmPassword": "123456",
    "role": "user"
}

###
//get all user
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJadW1hcmRpIFJhaG1hbiIsImdlbmRlciI6Ik1hbGUiLCJlbWFpbCI6Inp1bWFyMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE2NjU5NDI4NDcsImV4cCI6MTY2NTk0Mjg2Mn0.2l7uJgAIK9hNSETtGPlc5erGpvjxf2X0NxwwlCu6PwU
###
//get singel user
GET http://localhost:5000/users/bb9cf2cf-39c2-4c6f-911a-912ff54fa678
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJadW1hcmRpIFJhaG1hbiIsImdlbmRlciI6Ik1hbGUiLCJlbWFpbCI6Inp1bWFyMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE2NjU5NDI4NzYsImV4cCI6MTY2NTk0Mjg5MX0.2xJOSiPctSaRqDcMt_n_FAgbIdLuO6AQA3RjrVuYBXw


###
//update user
PATCH  http://localhost:5000/users/bb9cf2cf-39c2-4c6f-911a-912ff54fa678
Content-Type: application/json

{
    "name":"Indah Hariani",
    "email": "indah@gmail.com",
    "gender": "Female",
    "password": "",
    "confirmPassword": "",
    "role": "user"
}

###
//delete user
DELETE  http://localhost:5000/users/64c2e8b1-b514-46f9-b607-a0224baf5c70

### 
//login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "zumar2014@gmail.com",
    "password": "123456"
}

### 
//Akses Me
GET http://localhost:5000/me

### 
//Akses Me
DELETE http://localhost:5000/logout