GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJadW1hcmRpIFJhaG1hbiIsImdlbmRlciI6Ik1hbGUiLCJlbWFpbCI6Inp1bWFyMjAxNEBnbWFpbC5jb20iLCJpYXQiOjE2NjU4MTMwMjMsImV4cCI6MTY2NTgxMzA0M30.m3ju_fggFDV0azV_Wela69f2XQTeVpsV8FFqSntGqIs
###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Zumardi rahman",
    "email": "zumar2014@gmail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:5000/users/6
Content-Type: application/json

{
    "name":"Indah Hariani",
    "email": "indahhariani@gmail.com",
    "gender": "Female"
}

###
DELETE  http://localhost:5000/users/5


###
POST http://localhost:5000/register
Content-Type: application/json

{
    "name":"Zumardi Rahmanx",
    "email": "zumar2014@gmail.come",
    "gender": "Male",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "zumar2014@gmail.com",
    "password": "123456"
}


###
GET http://localhost:5000/token


###
DELETE  http://localhost:5000/logout